---
- hosts: localhost
  vars:
    nios_provider:
      host: 10.196.205.10
      username: cloudadmin
      password: infoblox
      wapi_version: "2.12"

  connection: local
  tasks:
  - name: 'create DTC Pool'
    infoblox.nios_modules.nios_dtc_pool:
      name: Pool1
      lb_preferred_method: ROUND_ROBIN
      servers:
      - server: Server1
        ratio: 1
      monitors:
      - name: monitor1
        type: icmp
      comment: Created with Ansible
      state: present
      provider: "{{ nios_provider }}"
...
