---
- hosts: localhost
  vars:
    nios_provider:
      host: 10.196.205.10
      username: cloudadmin
      password: infoblox
      wapi_version: "2.12"

  connection: local
  tasks:
  - name: 'create DTC LBDN'
    infoblox.nios_modules.nios_dtc_lbdn:
      name: LBDN1
      lb_method: GLOBAL_AVAILABILITY
      pools:
      - pool: Pool1
        ratio: 2
      ttl: 100
      auth_zones: 
      - 'demo.com'
      patterns: 
      - '*.demo.com'
      types:
      - A
      comment: Created with Ansible
      state: present
      provider: "{{ nios_provider }}"
... 
