---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: create DNS view
     infoblox.nios_modules.nios_dns_view:
       name: ansibleDnsView
       network_view: ansibleCollectionsView
       extattrs:
         Site: Test Site
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
