---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: Create Nios A record Test
     infoblox.nios_modules.nios_a_record:
       name: v55.ansibletestzone.com
       view: ansibleDnsView
       ipv4: 192.168.11.251
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
