---
- name: Configure nios extensible attribute
  hosts: localhost
  vars:
    nios_provider:
      host: 10.120.1.11
      username: admin
      password: infoblox

  connection: local
  tasks:
    - name: Create INT extensible attribute
      infoblox.nios_modules.nios_extensible_attribute:
        name: integer_ea
        type: INTEGER
        default_value: 11
        comment: Created with Ansible
        flags: I
        state: present
        provider: "{{ nios_provider }}"
