---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
    - name: Delete Nios DTC SNMP monitor Test
      infoblox.nios_modules.nios_dtc_monitor_snmp:
        name: snmp_monitor
        state: absent
        provider: "{{ nios_provider }}"
