---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: delete network view
     infoblox.nios_modules.nios_network_view:
       name: ansibleNetView
       state: absent
       provider: "{{ nios_provider }}"
