---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
    - name: Delete Nios DTC ICMP monitor Test
      infoblox.nios_modules.nios_dtc_monitor_icmp:
        name: icmp_monitor
        state: absent
        provider: "{{ nios_provider }}"
