---
  
- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: Create Nios TXT record
     infoblox.nios_modules.nios_txt_record:
       name: fqdn.txt.ansible.com
       text: example_text
       view: default
       comment: Created with Ansible
       state: absent
       provider: "{{ nios_provider }}"
