---
- name: Infoblox Member Configuration
  hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
    - name: Delete Nios DTC SIP monitor Test
      infoblox.nios_modules.nios_dtc_monitor_sip:
        name: sip_monitor
        port: 8080
        state: absent
        provider: "{{ nios_provider }}"
