---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: delete zone
     infoblox.nios_modules.nios_zone:
       name: ansiblezone.com
       view: ansibleDnsView
       state: absent
       provider: "{{ nios_provider }}"
