---
  
- hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2 
      username: cloudadmin
      password: admin

  connection: local
  tasks:
   - name: Create Nios MX record
     infoblox.nios_modules.nios_mx_record:
       name: ansible.com
       mx: mailhost.ansible.com
       preference: 0
       comment: Created with Ansible
       state: absent
       provider: "{{ nios_provider }}"
